[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts', '@chainlink/contracts=lib/chainlink/contracts']
optimizer = true
optimizer_runs = 200

[profile.gas_reports]
enabled = true